# .github/workflows/build-macos.yml
# This workflow builds and releases the macOS app when a new release is created on GitHub.

name: Build and Release macOS App

on:
  release:
    types: [created] # **FIX:** This now triggers the workflow only when you create a release.

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Homebrew dependencies
        run: brew install displayplacer

      - name: Install Node.js dependencies
        run: npm install

      - name: Build and package the Electron app
        run: npm run dist
        env:
          # The secret token is passed here, allowing electron-builder to create a release
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload macOS App Artifact to Release
        # This step is now more explicit about uploading to the release that triggered the workflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/simpleres-1.0.0-arm64.dmg
          asset_name: SimpleRes-${{ github.ref_name }}.dmg
          asset_content_type: application/octet-stream
