# .github/workflows/build-macos.yml
# This workflow builds the SimpleRes macOS app on every push to the main branch.

name: Build macOS App

on:
  push:
    branches: [ main ] # Ensure this matches your default branch name (e.g., main or master)

jobs:
  build:
    # Use a specific version of macOS for long-term stability
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Add caching for faster builds

      - name: Install Homebrew dependencies
        run: brew install displayplacer

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile the screenresolution tool
        run: make

      - name: Build and package the Electron app
        run: npm run dist
        env:
          # This is required by electron-builder for code signing on macOS
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload macOS App Artifact
        # **FIX:** Updated to the latest version (v4) to resolve the deprecation error
        uses: actions/upload-artifact@v4
        with:
          name: SimpleRes-macOS
          path: dist/*.dmg # Upload the distributable DMG file
